language: java

install:
  - git fetch --tags

script:
  - ./gradlew assemble test

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -f $HOME/.gradle/caches/2.10/plugin-resolution/cache.properties
  - rm -f $HOME/.gradle/caches/2.10/plugin-resolution/cache.properties.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/